### ISSUE TITLE
Generate infinite loop

### ISSUE THREAD

**Issue by ZettaXZycho** [Lartu/lartype#2]
![image](https://user-images.githubusercontent.com/21963604/45511371-3e59e180-b773-11e8-86de-59d35b86cb9a.png)
![image](https://user-images.githubusercontent.com/21963604/45511393-487be000-b773-11e8-95aa-3b38d967e404.png)
Second one happened after changing /usr/local/bin to ~/bin in Generate. It's also an infinite loop.

**Comment by Lartu** [comment]
Looking into it, thank you very much!

**Comment by Lartu** [comment]
Fixed in 3.1
